import { useState } from 'react';
import { employeeAPI } from '../api';
import toast from 'react-hot-toast';
import { QRCodeCanvas } from 'qrcode.react';

export default function QRModal({ employee, onClose }) {
  const [loading, setLoading] = useState(false);

  if (!employee) return null;

  // Extract token from the default profile URL generated by backend
  const secureToken = employee.profile_url.split('/').pop().split('#')[0];
  const [githubUrl, setGithubUrl] = useState('');

  const currentQRValue = githubUrl 
    ? githubUrl.trim()
    : employee.profile_url; // Default to backend URL if empty

  const handleDownloadPNG = () => {
    const canvas = document.getElementById('employee-qr-canvas');
    if (!canvas) {
      toast.error('QR code not rendered yet');
      return;
    }
    const link = document.createElement('a');
    link.href = canvas.toDataURL('image/png');
    link.download = `QR_${employee.employee_id}_${employee.name.replace(/\s+/g,'_')}.png`;
    link.click();
    toast.success('QR downloaded as PNG');
  };

  const handleDownloadSVG = async () => {
    setLoading(true);
    try {
      const res = await employeeAPI.getQR(employee.employee_id, 'svg');
      const blob = new Blob([res.data], { type: 'image/svg+xml' });
      const url  = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `QR_${employee.employee_id}.svg`;
      link.click();
      URL.revokeObjectURL(url);
      toast.success('QR downloaded as SVG');
    } catch {
      toast.error('SVG download failed');
    } finally {
      setLoading(false);
    }
  };

  const handlePrint = () => {
    const win = window.open('', '_blank');
    const canvas = document.getElementById('employee-qr-canvas');
    const qrDataUrl = canvas ? canvas.toDataURL('image/png') : employee.qr_data;

    win.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>QR Code – ${employee.name}</title>
          <style>
            body { font-family: Inter, sans-serif; display: flex; flex-direction: column; align-items: center; justify-content: center; min-height: 100vh; margin: 0; background: #fff; }
            .card { border: 2px solid #6366f1; border-radius: 16px; padding: 24px 32px; text-align: center; width: 260px; }
            img { width: 200px; height: 200px; }
            h2 { margin: 12px 0 4px; font-size: 16px; color: #1e1e2e; }
            p  { margin: 2px 0; font-size: 13px; color: #555; }
            .id { font-size: 11px; color: #888; margin-top: 8px; font-family: monospace; }
            .logo { font-size: 11px; font-weight: 700; letter-spacing: 2px; color: #6366f1; margin-bottom: 8px; }
          </style>
        </head>
        <body>
          <div class="card">
            <img src="${window.location.origin}/logo.png" alt="WE GUIDE Logo" style="width: 140px; height: auto; margin-bottom: 12px; border-radius: 4px;" />
            <img src="${qrDataUrl}" alt="QR Code" />
            <h2>${employee.name}</h2>
            <p>${employee.designation}</p>
            <p>${employee.department}</p>
            <div class="id">ID: ${employee.employee_id}</div>
          </div>
          <script>window.onload = () => { window.print(); window.close(); }</script>
        </body>
      </html>
    `);
    win.document.close();
    toast.success('Print dialog opened');
  };

  const handleDownloadStaticHTML = () => {
    const initials = employee.name.split(' ').map(w => w[0]).join('').toUpperCase().slice(0, 2);
    const dob = employee.dob ? new Date(employee.dob).toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' }) : '—';
    
    const staticHTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
  <title>${employee.name} - WE GUIDE</title>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet" />
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    :root { --bg:#0d1117; --surface:#161b22; --card:#21262d; --accent:#6e40c9; --accent2:#a855f7; --emerald:#10b981; --red:#ef4444; --text:#f0f6fc; --muted:#8b949e; --border:#30363d; --radius:16px; }
    body { font-family: 'Inter', sans-serif; background: var(--bg); color: var(--text); min-height: 100vh; display: flex; flex-direction: column; align-items: center; padding: 0 0 40px; }
    .header { width: 100%; background: linear-gradient(135deg, var(--accent) 0%, #9333ea 100%); padding: 32px 20px 60px; text-align: center; position: relative; overflow: hidden; }
    .header::before { content: ''; position: absolute; inset: 0; background: url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23ffffff' fill-opacity='0.05'%3E%3Ccircle cx='30' cy='30' r='20'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E"); }
    .header .logo { font-size: 13px; font-weight: 700; letter-spacing: 3px; text-transform: uppercase; opacity: .7; position: relative; }
    .header h1 { font-size: 26px; font-weight: 800; margin-top: 8px; position: relative; }
    .header .subtitle { font-size: 13px; opacity: .75; margin-top: 4px; position: relative; }
    .avatar-wrap { display: flex; justify-content: center; margin-top: -36px; }
    .avatar { width: 72px; height: 72px; border-radius: 50%; background: linear-gradient(135deg, var(--accent), var(--accent2)); border: 4px solid var(--surface); display: flex; align-items: center; justify-content: center; font-size: 28px; font-weight: 800; color: #fff; box-shadow: 0 8px 24px rgba(110,64,201,.4); }
    .card { background: var(--card); border: 1px solid var(--border); border-radius: var(--radius); margin: 16px 16px 0; padding: 20px; max-width: 440px; width: calc(100% - 32px); }
    .card-title { font-size: 11px; font-weight: 700; letter-spacing: 2px; text-transform: uppercase; color: var(--muted); margin-bottom: 16px; }
    .row { display: flex; gap: 10px; margin-bottom: 12px; align-items: flex-start; }
    .row .icon { width: 36px; height: 36px; border-radius: 10px; background: rgba(110,64,201,.15); display: flex; align-items: center; justify-content: center; font-size: 16px; flex-shrink: 0; }
    .row .content .label { font-size: 11px; color: var(--muted); font-weight: 500; }
    .row .content .value { font-size: 15px; font-weight: 600; color: var(--text); margin-top: 2px; }
    .badge { display: inline-flex; align-items: center; gap: 4px; padding: 4px 10px; border-radius: 20px; font-size: 12px; font-weight: 600; background: rgba(110,64,201,.2); color: var(--accent2); border: 1px solid rgba(110,64,201,.3); margin-top: 4px; }
    .sos-card { background: linear-gradient(135deg, rgba(239,68,68,.15), rgba(239,68,68,.05)); border-color: rgba(239,68,68,.3); }
    .sos-btn { display: flex; align-items: center; justify-content: center; gap: 10px; background: var(--red); color: #fff; border: none; border-radius: 14px; padding: 16px 24px; font-family: 'Inter', sans-serif; font-size: 16px; font-weight: 700; width: 100%; cursor: pointer; text-decoration: none; transition: all .2s; box-shadow: 0 4px 20px rgba(239,68,68,.4); animation: pulse 2s infinite; }
    .sos-btn:hover { transform: scale(1.02); box-shadow: 0 6px 28px rgba(239,68,68,.6); }
    .sos-btn:active { transform: scale(.98); }
    @keyframes pulse { 0%, 100% { box-shadow: 0 4px 20px rgba(239,68,68,.4); } 50% { box-shadow: 0 4px 30px rgba(239,68,68,.7); } }
    .sos-hint { text-align: center; font-size: 12px; color: var(--muted); margin-top: 10px; }
    .footer { text-align: center; font-size: 12px; color: var(--muted); margin-top: 24px; }
    .footer strong { color: var(--accent2); }
  </style>
</head>
<body>
  <div id="app">
    <div class="header">
      <div class="logo">WE GUIDE</div>
      <h1>${employee.name}</h1>
      <div class="subtitle">${employee.designation} &bull; ${employee.department}</div>
    </div>
    <div class="avatar-wrap"><div class="avatar">${initials}</div></div>
    
    <div class="card" style="margin-top:20px">
      <div class="card-title">👤 Personal Information</div>
      <div class="row"><div class="icon">🗓️</div><div class="content"><div class="label">Date of Birth</div><div class="value">${dob}</div></div></div>
      <div class="row"><div class="icon">⚧</div><div class="content"><div class="label">Gender</div><div class="value">${employee.gender || '—'}</div></div></div>
      <div class="row"><div class="icon">🏢</div><div class="content"><div class="label">Department</div><div class="badge">🏷️ ${employee.department || '—'}</div></div></div>
    </div>
    
    <div class="card">
      <div class="card-title">📞 Contact</div>
      <div class="row"><div class="icon">📱</div><div class="content"><div class="label">Phone Number</div><div class="value"><a href="tel:${employee.phone}" style="color:var(--accent2);text-decoration:none">${employee.phone || '—'}</a></div></div></div>
    </div>
    
    <div class="card sos-card">
      <div class="card-title">🆘 Emergency Contact</div>
      <div class="row"><div class="icon">🚨</div><div class="content"><div class="label">Emergency Number</div><div class="value">${employee.emergency_contact || '—'}</div></div></div>
      <a href="tel:${employee.emergency_contact}" class="sos-btn">🆘 &nbsp;SOS — CALL NOW</a>
      <p class="sos-hint">Tap to immediately call the emergency contact</p>
    </div>
    
    <div class="footer">Powered by <strong>WE GUIDE</strong> &bull; Employee Management System</div>
  </div>
</body>
</html>`;

    const blob = new Blob([staticHTML], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${employee.name}.html`;
    link.click();
    URL.revokeObjectURL(url);
    toast.success('Static HTML downloaded! You can upload this to GitHub.');
  };

  return (
    <div className="modal-overlay" onClick={(e) => e.target === e.currentTarget && onClose()}>
      <div className="modal" style={{ maxWidth: 480 }}>
        <div className="modal-header">
          <div className="modal-title">
            <span>🔳</span>
            QR Code — {employee.name}
          </div>
          <button className="btn btn-ghost btn-icon" onClick={onClose}>✕</button>
        </div>

        <div className="modal-body" style={{ textAlign: 'center' }}>
          {/* Employee Info */}
          <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 24, textAlign: 'left', background: 'var(--surface2)', borderRadius: 10, padding: '12px 16px' }}>
            <div className="avatar avatar-lg">{employee.name.split(' ').map(w=>w[0]).join('').toUpperCase().slice(0,2)}</div>
            <div>
              <div style={{ fontWeight: 700, fontSize: 16 }}>{employee.name}</div>
              <div style={{ fontSize: 13, color: 'var(--text2)' }}>{employee.designation} • {employee.department}</div>
              <div style={{ fontSize: 12, color: 'var(--text3)', fontFamily: 'JetBrains Mono, monospace' }}>ID: {employee.employee_id}</div>
            </div>
          </div>

          {/* QR Code */}
          <div className="qr-container" style={{ margin: '0 auto 20px', background: '#fff', padding: '16px', borderRadius: '12px', display: 'inline-block' }}>
            <QRCodeCanvas 
              id="employee-qr-canvas"
              value={currentQRValue} 
              size={220} 
              level="H"
              includeMargin={false}
            />
          </div>

          {/* GitHub Configurator */}
          <div style={{ background: 'rgba(16, 185, 129, 0.1)', border: '1px solid rgba(16, 185, 129, 0.3)', borderRadius: 10, padding: '16px', marginBottom: 24, textAlign: 'left' }}>
            <div style={{ fontSize: 13, fontWeight: 600, color: '#34d399', marginBottom: 8 }}>
              🔗 Connect to GitHub Pages
            </div>
            <p style={{ fontSize: 12, color: 'var(--text2)', marginBottom: 12 }}>
              If you uploaded this employee's HTML file to GitHub, paste the public link below. We will instantly update the QR Code above to point directly to that link without any tokens.
            </p>
            <input 
              type="url" 
              className="form-control" 
              placeholder="e.g., https://your-name.github.io/Profile_EMP001.html" 
              value={githubUrl}
              onChange={(e) => setGithubUrl(e.target.value)}
              style={{ fontSize: 12 }}
            />
            {githubUrl && (
              <div style={{ fontSize: 11, color: 'var(--text3)', marginTop: 8, fontFamily: 'monospace', wordBreak: 'break-all' }}>
                <strong>QR Payload:</strong> {currentQRValue}
              </div>
            )}
          </div>

          {/* Info labels */}
          <div style={{ display: 'flex', gap: 8, justifyContent: 'center', marginBottom: 24, flexWrap: 'wrap' }}>
            <span className="badge badge-purple">📷 Attendance Scan</span>
            <span className="badge badge-cyan">🌐 Public Profile</span>
          </div>

          <p style={{ fontSize: 12, color: 'var(--text3)', marginBottom: 20 }}>
            When scanned internally → marks attendance.&nbsp;
            When scanned via phone camera → opens public profile page.
          </p>

          {/* Actions */}
          <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap', justifyContent: 'center' }}>
            <button className="btn btn-primary btn-sm" onClick={handleDownloadPNG}>
              ⬇️ Download PNG
            </button>
            <button className="btn btn-secondary btn-sm" onClick={handleDownloadSVG} disabled={loading}>
              {loading ? '…' : '⬇️ Download SVG'}
            </button>
            <button className="btn btn-secondary btn-sm" onClick={handlePrint}>
              🖨️ Print / ID Card
            </button>
            <button className="btn btn-secondary btn-sm" onClick={() => window.open(employee.profile_url, '_blank')}>
              🌐 Open Server Link
            </button>
            <button className="btn btn-primary btn-sm" onClick={handleDownloadStaticHTML} style={{ background: '#10b981', color: '#000' }}>
              📄 Download GitHub HTML
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
